version: '3.8'

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "acm_gisma"
    ports:
      - "3306:3306"
    networks:
      - app-network
  mongodb:
    image: mongo:8.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    ports:
      - "27017:27017"
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: gisma-acm-server/Dockerfile
    image: gisma-acm-server
    environment:
      # MYSQL Connection Information
      - MYSQL_URL=mysql://mysql_db:3306/acm_gisma
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      # MongoDB Connection Information
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_HOST=mongo_db:27017
      - MONGODB_DATABASE=acm_gisma
      # Admin User Data
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@gisma.com
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
